QuizBuilder/QuizBuilder/Models/Quiz.cs
using System;
using System.Collections.Generic;

namespace QuizBuilder.Models
{
    public partial class Quiz
    {
        public Quiz()
        {
            this.QuizAttempts = new List<QuizAttempt>();
            this.Scenarios = new List<Scenario>();
        }

        public int QuizID { get; set; }
        public string QuizAuthor { get; set; }
        public string QuizName { get; set; }
        public int QuestionPoolID { get; set; }
        public virtual ICollection<QuizAttempt> QuizAttempts { get; set; }
        public virtual ICollection<Scenario> Scenarios { get; set; }
    }
}

QuizBuilder/QuizBuilder/Controllers/QuizController.cs
using QuizBuilder.Models;
using QuizBuilder.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace QuizBuilder.Controllers
{
    [Authorize]
    public class QuizController : Controller
    {
        public ActionResult ListQuiz()
        {
            var quizzes = QuizService.GetQuizzes();
            if (quizzes == null)
                quizzes = new Quiz[0];
            return PartialView(quizzes);
        }

        public ActionResult ChooseQuiz()
        {
            var quizzes = QuizService.GetQuizzes();
            if (quizzes == null)
                quizzes = new Quiz[0];
            return View("ListQuiz", quizzes);
        }

        [Authorize(Roles = "admin")]
        public ActionResult CreateQuiz()
        {
            return PartialView();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateQuiz(Quiz model)
        {
            if (ModelState.IsValid)
            {
                QuizService.AddQuiz(model);
                return RedirectToAction("Default");
            }
            else
            {
                return RedirectToAction("Default");
            }
        }

        [Authorize(Roles = "admin")]
        public ActionResult ManageQuiz(int quizId)
        {
            var quiz = QuizService.FindQuiz(quizId);
            if (quiz != null)
                return View(quiz);
            else
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ManageQuiz(Quiz model)
        {
            if (ModelState.IsValid)
            {
                QuizService.UpdateQuiz(model);
            }
            return RedirectToAction("Home", "User");
        }

        public ActionResult NewQuiz(int quizId)
        {
            QuizAttempt newAttempt = new QuizAttempt { UserID = UserService.FindByName(User.Identity.Name).UserID, QuizID = quizId, QuizDate = DateTime.Now };
            newAttempt = QuizService.AddQuizAttempt(newAttempt);
            int[] quizScenarioIds = ScenarioService.GetScenarios().Where(s => s.QuizID == quizId).Select(s => s.ScenarioID).ToArray();
            Question[] questionArray = QuestionService.GetQuestions().Where(q => quizScenarioIds.Contains(q.ScenarioID)).ToArray();
            ViewData.Add("QuestionArray", questionArray);
            ViewData.Add("SelectedQuestion", questionArray[0].QuestionID);
            return View("TakeQuiz", newAttempt);
        }

        public ActionResult TakeQuiz(int quizAttemptId, int? questionId)
        {
            QuizAttempt quizAttempt = QuizService.FindQuizAttempt(quizAttemptId);
            Quiz quiz = QuizService.FindQuiz(quizAttempt.QuizID);
            Scenario scenario = ScenarioService.FindScenario(quiz.QuizID);
            int[] quizScenarioIds = ScenarioService.GetScenarios().Where(s => s.QuizID == quiz.QuizID).Select(s => s.ScenarioID).ToArray();
            Question[] questionArray = QuestionService.GetQuestions().Where(q => quizScenarioIds.Contains(q.ScenarioID)).ToArray();
            ViewData.Add("QuestionArray", questionArray);
            if (questionId == null)
                ViewData.Add("SelectedQuestion", questionArray[0].QuestionID);
            else
                ViewData.Add("SelectedQuestion", (int)questionId);
            return View(quizAttempt);
        }

        public ActionResult ShowQuestion(int quizAttemptId, int questionId)
        {
            ViewData.Add("Question", QuestionService.FindQuestion(questionId));
            ViewData.Add("QuestionOptions", QuestionService.FindOptions(questionId));
            ViewData.Add("Attempt", QuizService.FindQuizAttempt(quizAttemptId));
            QuestionResponse[] existingResponse = QuestionService.GetResponses(quizAttemptId).Where(r => r.QuestionID == questionId).ToArray();
            if (existingResponse != null && existingResponse.Length == 1)
                ViewData.Add("ExistingResponse", existingResponse[0]);
            return PartialView();
        }

        public ActionResult PickQuestion(int quizAttemptId, int questionOptionId)
        {
            QuestionOption chosenOption = QuestionService.FindOption(questionOptionId);
            QuestionResponse[] existingResponse = QuestionService.GetResponses(quizAttemptId).Where(r => r.QuestionID == chosenOption.QuestionID).ToArray();
            if (existingResponse == null || existingResponse.Length == 0)
            {
                QuestionService.AddResponse(new QuestionResponse
                {
                    QuestionID = chosenOption.QuestionID,
                    QuestionOptionID = chosenOption.QuestionOptionID,
                    QuizAttemptID = quizAttemptId,
                    IsCorrect = chosenOption.IsCorrect,
                    UserReviewFlag = false
                });
                return RedirectToAction("TakeQuiz", new { quizAttemptId = quizAttemptId });
            }
            if (existingResponse != null && existingResponse.Length == 1)
            {
                existingResponse[0].QuestionOptionID = questionOptionId;
                QuestionService.UpdateResponse(existingResponse[0]);
                return RedirectToAction("TakeQuiz", new { quizAttemptId = quizAttemptId });
            }
            return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
        }

        public ActionResult ResultsQuiz()
        {
            QuizAttempt[] attempts = QuizService.GetUserAttempts(UserService.FindByName(User.Identity.Name).UserID);
            return View(attempts);
        }

        public ActionResult FinishQuiz(int quizAttemptId)
        {
            QuizAttempt attempt = QuizService.FindQuizAttempt(quizAttemptId);
            QuestionResponse[] responses = QuestionService.GetResponses(quizAttemptId);
            int score = (responses.Length / responses.Where(r => r.IsCorrect == true).ToArray().Length) * 100;
            attempt.Score = score;
            QuizService.UpdateQuizAttempt(attempt);
            return RedirectToAction("ResultsQuiz");
        }
    }
}

QuizBuilder/QuizBuilder/Controllers/ScenarioController.cs
using QuizBuilder.Models;
using QuizBuilder.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace QuizBuilder.Controllers
{
    [Authorize]
    public class ScenarioController : Controller
    {
        [Authorize(Roles = "admin")]
        public ActionResult ListScenario()
        {
            var scenarios = ScenarioService.GetScenarios();
            if (scenarios == null)
                scenarios = new Scenario[0];
            return PartialView(scenarios);
        }

        [Authorize(Roles = "admin")]
        public ActionResult CreateScenario()
        {
            SelectList quizList = new SelectList(QuizService.GetQuizzes(), "QuizID", "QuizName");
            ViewData.Add("QuizID", quizList);
            return PartialView();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateScenario(Scenario model)
        {
            if (ModelState.IsValid)
            {
                ScenarioService.AddScenario(model);
                return RedirectToAction("Home", "User");
            }
            else
            {
                return RedirectToAction("Home", "User");
            }
        }
        [Authorize(Roles = "admin")]
        public ActionResult ManageScenario(int scenarioId)
        {
            var scenario = ScenarioService.FindScenario(scenarioId);
            if (scenario != null)
            {
                SelectList quizList = new SelectList(QuizService.GetQuizzes(), "QuizID", "QuizName");
                foreach (SelectListItem q in quizList)
                {
                    if (q.Value == scenario.QuizID.ToString())
                        q.Selected = true;
                }
                ViewData.Add("QuizID", quizList);
                return View(scenario);
            }
            else
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ManageScenario(Scenario model)
        {
            if (ModelState.IsValid)
            {
                ScenarioService.UpdateScenario(model);
            }
            return RedirectToAction("Home", "User");
        }
    }
}

QuizBuilder/QuizBuilder/Views/Quiz/CreateQuiz.cshtml
@model QuizBuilder.Models.Quiz

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Quiz</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.QuizAuthor, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuizAuthor)
                @Html.ValidationMessageFor(model => model.QuizAuthor)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuizName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuizName)
                @Html.ValidationMessageFor(model => model.QuizName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuestionPoolID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuestionPoolID)
                @Html.ValidationMessageFor(model => model.QuestionPoolID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

QuizBuilder/QuizBuilder/Views/Quiz/ListQuiz.cshtml
@model IEnumerable<QuizBuilder.Models.Quiz>
@if(User.IsInRole("admin"))
{ 
@Html.ActionLink("Create New", "CreateQuiz", null, new { @class = "btn btn-default", @style = "margin: 5px" })
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.QuizAuthor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QuizName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QuestionPoolID)
        </th>
        @if(User.IsInRole("admin"))
        { 
        <th></th>
        }
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.QuizAuthor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuizName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuestionPoolID)
            </td>
            @if(User.IsInRole("admin"))
            { 
            <td>
                @Html.ActionLink("Manage", "ManageQuiz", "Quiz", new {quizId = item.QuizID }, new { @class = "btn btn-default", @style = "margin: 5px" })
            </td>
            }
            <td>
                @Html.ActionLink("Take", "NewQuiz", "Quiz", new { quizId = item.QuizID }, new { @class = "btn btn-default", @style = "margin: 5px" })  
            </td>
        </tr>
    }
</table>

QuizBuilder/QuizBuilder/Views/Quiz/ManageQuiz.cshtml
@model QuizBuilder.Models.Quiz

@{
    ViewBag.Title = "Manage Quiz";
}

<h2>View1</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Quiz</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.QuizID)

        <div class="form-group">
            @Html.LabelFor(model => model.QuizAuthor, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuizAuthor)
                @Html.ValidationMessageFor(model => model.QuizAuthor)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuizName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuizName)
                @Html.ValidationMessageFor(model => model.QuizName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuestionPoolID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuestionPoolID)
                @Html.ValidationMessageFor(model => model.QuestionPoolID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@Html.Action("ListScenario", "Scenario")
@Html.Action("CreateScenario", "Scenario")

QuizBuilder/QuizBuilder/Views/Quiz/ResultsQuiz.cshtml
@model IEnumerable<QuizBuilder.Models.QuizAttempt>

@{
    ViewBag.Title = "ResultsQuiz";
}

<h2>ResultsQuiz</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.QuizDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Score)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.QuizDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Score)
        </td>
        <td>
        </td>
    </tr>
}

</table>

QuizBuilder/QuizBuilder/Views/Quiz/ShowQuestion.cshtml
@using QuizBuilder.Models

<div class="panel-body">
    <h3>@(((Question)ViewData["Question"]).QuestionContent)</h3>
    <div class="btn-group-vertical">
        @foreach (QuestionOption option in (QuestionOption[])ViewData["QuestionOptions"])
        {
            if ((QuestionResponse)ViewData["ExistingResponse"] != null)
            {
                QuestionResponse existingResponse = (QuestionResponse)ViewData["ExistingResponse"];
                if (existingResponse.QuestionOptionID == option.QuestionOptionID)
                {
                    @Html.ActionLink(option.OptionText, "PickQuestion", "Quiz", new { quizAttemptId = ((QuizAttempt)ViewData["Attempt"]).QuizAttemptID, questionOptionId = option.QuestionOptionID }, new { @class = "btn btn-default active" })
                }
                else
                {
                    @Html.ActionLink(option.OptionText, "PickQuestion", "Quiz", new { quizAttemptId = ((QuizAttempt)ViewData["Attempt"]).QuizAttemptID, questionOptionId = option.QuestionOptionID }, new { @class = "btn btn-default" })
                }
            }
            else
            {
                @Html.ActionLink(option.OptionText, "PickQuestion", "Quiz", new { quizAttemptId = ((QuizAttempt)ViewData["Attempt"]).QuizAttemptID, questionOptionId = option.QuestionOptionID }, new { @class = "btn btn-default" })
            }
        }
    </div>
</div>

QuizBuilder/QuizBuilder/Views/Quiz/TakeQuiz.cshtml
@using QuizBuilder.Models

@model QuizBuilder.Models.QuizAttempt
@{
    ViewBag.Title = "UserQuizzes";
}

<div class="container">
    <div class="jumbotron">
        <h1>QuizBuilder</h1>
        <p>Welcome to QuizBuilder! The best site for taking quizzes on the internet!</p>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <ul class="pagination">
                <li><a href="#">&laquo;</a></li>
                @for (int i = 0; i < ((Question[])ViewData["QuestionArray"]).Length; i++ )
                {
                    <li>@Html.ActionLink(i.ToString(), "ShowQuestion", new { quizAttemptId = Model.QuizAttemptID, questionId = (((Question[])ViewData["QuestionArray"])[i]).QuestionID })</li>
                }
                <li><a href="#">&raquo;</a></li>
            </ul>
        </div>
        <div class="panel-body">
            @Html.Action("ShowQuestion", new {quizAttemptId = Model.QuizAttemptID, questionId = (int)ViewData["SelectedQuestion"] })
        </div>
    </div>
    @Html.ActionLink("Finish Quiz", "FinishQuiz", new { quizAttemptId = Model.QuizAttemptID }, new { @class = "btn btn-default" })
</div>