QuizBuilder/QuizBuilder/Models/Scenario.cs
using System;
using System.Collections.Generic;

namespace QuizBuilder.Models
{
    public partial class Scenario
    {
        public Scenario()
        {
            this.Questions = new List<Question>();
        }

        public int ScenarioID { get; set; }
        public int QuizID { get; set; }
        public int ScenarioSequence { get; set; }
        public string ScenarioName { get; set; }
        public string ScenarioText { get; set; }
        public bool IsRichText { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual Quiz Quiz { get; set; }
    }
}

QuizBuilder/QuizBuilder/Controllers/QuestionController.cs
using QuizBuilder.Models;
using QuizBuilder.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace QuizBuilder.Controllers
{
    [Authorize]
    public class QuestionController : Controller
    {
        [Authorize(Roles = "admin")]
        public ActionResult ListQuestion()
        {
            var questions = QuestionService.GetQuestions();
            if (questions == null)
                questions = new Question[0];
            return PartialView(questions);
        }

        [Authorize(Roles = "admin")]
        public ActionResult CreateQuestion()
        {
            SelectList scenarioList = new SelectList(ScenarioService.GetScenarios(), "ScenarioID", "ScenarioName");
            ViewData.Add("ScenarioID", scenarioList);
            return PartialView();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateQuestion(Question model)
        {
            if (ModelState.IsValid)
            {
                QuestionService.AddQuestion(model);
                return RedirectToAction("Home", "User");
            }
            else
            {
                return RedirectToAction("Home", "User");
            }
        }

        [Authorize(Roles = "admin")]
        public ActionResult ManageQuestion(int questionId)
        {
            var scenario = QuestionService.FindQuestion(questionId);
            if (scenario != null)
            {
                QuestionOption[] optionList = QuestionService.FindOptions(questionId);
                SelectList scenarioList = new SelectList(ScenarioService.GetScenarios(), "ScenarioID", "ScenarioName");
                foreach (SelectListItem q in scenarioList)
                {
                    if (q.Value == scenario.ScenarioID.ToString())
                        q.Selected = true;
                }
                ViewData.Add("ScenarioID", scenarioList);
                ViewData.Add("Options", optionList);
                return View(scenario);
            }
            else
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ManageQuestion(Question model)
        {
            if (ModelState.IsValid)
            {
                QuestionService.UpdateQuestion(model);
            }
            return RedirectToAction("Home", "User");
        }

        [Authorize(Roles = "admin")]
        public ActionResult ListOption(int questionId)
        {
            var options = QuestionService.FindOptions(questionId);
            if (options == null)
                options = new QuestionOption[0];
            return PartialView(options);
        }

        [Authorize(Roles = "admin")]
        public ActionResult CreateOption(int questionId)
        {
            ViewData.Add("QuestionID", questionId);
            return PartialView();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOption(QuestionOption model)
        {
            if (ModelState.IsValid)
            {
                QuestionService.AddOption(model);
                return RedirectToAction("Home", "User");
            }
            else
            {
                return RedirectToAction("Home", "User");
            }
        }

        [Authorize(Roles = "admin")]
        public ActionResult ManageOption(int questionId, int optionId)
        {
            var option = QuestionService.FindOption(optionId);
            if (option != null)
            {
                SelectList scenarioList = new SelectList(QuestionService.GetQuestions(), "QuestionID", "QuestionID");
                foreach (SelectListItem q in scenarioList)
                {
                    if (q.Value == option.QuestionID.ToString())
                        q.Selected = true;
                }
                ViewData.Add("QuestionID", questionId);
                return PartialView(option);
            }
            else
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ManageOption(QuestionOption model)
        {
            if (ModelState.IsValid)
            {
                QuestionService.UpdateOption(model);
            }
            return RedirectToAction("Home", "User");
        }
	}
}

QuizBuilder/QuizBuilder/Controllers/ScenarioController.cs
using QuizBuilder.Models;
using QuizBuilder.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace QuizBuilder.Controllers
{
    [Authorize]
    public class ScenarioController : Controller
    {
        [Authorize(Roles = "admin")]
        public ActionResult ListScenario()
        {
            var scenarios = ScenarioService.GetScenarios();
            if (scenarios == null)
                scenarios = new Scenario[0];
            return PartialView(scenarios);
        }

        [Authorize(Roles = "admin")]
        public ActionResult CreateScenario()
        {
            SelectList quizList = new SelectList(QuizService.GetQuizzes(), "QuizID", "QuizName");
            ViewData.Add("QuizID", quizList);
            return PartialView();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateScenario(Scenario model)
        {
            if (ModelState.IsValid)
            {
                ScenarioService.AddScenario(model);
                return RedirectToAction("Home", "User");
            }
            else
            {
                return RedirectToAction("Home", "User");
            }
        }
        [Authorize(Roles = "admin")]
        public ActionResult ManageScenario(int scenarioId)
        {
            var scenario = ScenarioService.FindScenario(scenarioId);
            if (scenario != null)
            {
                SelectList quizList = new SelectList(QuizService.GetQuizzes(), "QuizID", "QuizName");
                foreach (SelectListItem q in quizList)
                {
                    if (q.Value == scenario.QuizID.ToString())
                        q.Selected = true;
                }
                ViewData.Add("QuizID", quizList);
                return View(scenario);
            }
            else
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ManageScenario(Scenario model)
        {
            if (ModelState.IsValid)
            {
                ScenarioService.UpdateScenario(model);
            }
            return RedirectToAction("Home", "User");
        }
    }
}

QuizBuilder/QuizBuilder/Views/Scenario/CreateScenario 1.cshtml
@model QuizBuilder.Models.Scenario

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Scenario</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.QuizID, "QuizID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("QuizID",@ViewData["QuizID"] as SelectList, String.Empty)
                @Html.ValidationMessageFor(model => model.QuizID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ScenarioSequence, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ScenarioSequence)
                @Html.ValidationMessageFor(model => model.ScenarioSequence)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ScenarioName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ScenarioName)
                @Html.ValidationMessageFor(model => model.ScenarioName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ScenarioText, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ScenarioText)
                @Html.ValidationMessageFor(model => model.ScenarioText)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsRichText, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsRichText)
                @Html.ValidationMessageFor(model => model.IsRichText)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

QuizBuilder/QuizBuilder/Views/Scenario/CreateScenario.cshtml
@model QuizBuilder.Models.Scenario

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Scenario</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.QuizID, "QuizID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("QuizID",@ViewData["QuizID"] as SelectList, String.Empty)
                @Html.ValidationMessageFor(model => model.QuizID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ScenarioSequence, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ScenarioSequence)
                @Html.ValidationMessageFor(model => model.ScenarioSequence)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ScenarioName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ScenarioName)
                @Html.ValidationMessageFor(model => model.ScenarioName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ScenarioText, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ScenarioText)
                @Html.ValidationMessageFor(model => model.ScenarioText)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsRichText, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsRichText)
                @Html.ValidationMessageFor(model => model.IsRichText)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

QuizBuilder/QuizBuilder/Views/Scenario/ListScenario.cshtml
@model IEnumerable<QuizBuilder.Models.Scenario>
@Html.ActionLink("Create New", "CreateScenario", null, new { @class = "btn btn-default", @style = "margin: 5px" })
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.QuizID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ScenarioSequence)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ScenarioName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ScenarioText)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsRichText)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.QuizID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ScenarioSequence)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ScenarioName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ScenarioText)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsRichText)
            </td>
            <td>
                @Html.ActionLink("Manage", "ManageScenario", "Scenario", new { scenarioId = item.ScenarioID }, new { @class = "btn btn-default", @style = "margin: 5px" })
            </td>
        </tr>
    }

</table>

QuizBuilder/QuizBuilder/Views/Scenario/ManageScenario.cshtml
@model QuizBuilder.Models.Scenario

@{
    ViewBag.Title = "ManageScenario";
}

<h2>ManageScenario</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Scenario</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ScenarioID)

        <div class="form-group">
            @Html.LabelFor(model => model.QuizID, "QuizID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("QuizID", @ViewData["QuizId"] as SelectList, String.Empty, new { @style = "margin-top:5px" })
                @Html.ValidationMessageFor(model => model.QuizID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ScenarioSequence, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ScenarioSequence)
                @Html.ValidationMessageFor(model => model.ScenarioSequence)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ScenarioName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ScenarioName)
                @Html.ValidationMessageFor(model => model.ScenarioName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ScenarioText, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ScenarioText)
                @Html.ValidationMessageFor(model => model.ScenarioText)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsRichText, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsRichText)
                @Html.ValidationMessageFor(model => model.IsRichText)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@Html.Action("ListQuestion", "Question", new { scenarioId = Model.ScenarioID })
@Html.Action("CreateQuestion", "Question", new { scenarioId = Model.ScenarioID })